### ISSUE TITLE
route:ferry and route:share_taxi

### ISSUE THREAD

**Issue by altilunium** [tracestrack/osm-routes-index#3]
Hello.

I discovered https://routes.tracestrack.com while preparing this week's edition of WeeklyOSM. After using this index, I have an idea.

I already maintained yet-another-OSM-routes-index (https://altilunium.github.io/bisangkot/), focusing on public transportation in Indonesia. The problem is, I have to manually query the Overpass server to update this index. 

Since OpenStreetMap Routes Index's route database is synced everyday (as stated on its homepage), I thought I could use this index to update Bisangkot's data more easily.

> How to contribute? There are many ways to contribute to the projects. Creating markdown pages. Make more route lists. 

How can I make route list for `route:ferry` and `route:share_taxi` ?

**Comment by quinncnl** [comment]
Hi, ferry and share_taxi routes are not supported at the moment. But I can export those too. I'll try to add support for those in next few days.

**Comment by quinncnl** [comment]
I've exported the data and updated the pages. Now you can see `shared_taxi` in https://routes.tracestrack.com/id/bus/all/ and ferry routes in https://routes.tracestrack.com/id/ferry/all/. You can also use the relevant json database directly!

**Comment by altilunium** [comment]
Thank you very much.

Now I can update bisangkot maps more easily.

![image](https://github.com/tracestrack/osm-routes-index/assets/70379302/246edf48-93b3-4cd0-a61f-c4f130eb65b6)
 
 Above : [March 4, 2023](https://altilunium.github.io/bisangkot/4-Mar-23/) data 
 Below : [June 8, 2023](https://altilunium.github.io/bisangkot/) data
 
 I wonder why relation [12181772](https://www.openstreetmap.org/relation/12181772) is missing from this list.
 
 
![image](https://github.com/tracestrack/osm-routes-index/assets/70379302/8ac827e3-6c9e-4d2c-9301-8586a0b19f65)
