### ISSUE TITLE
Someone mentioned on Mastodon that some of the numbers here don't pass the smell test...

### ISSUE THREAD

**Issue by SomeoneElseOSM** [tracestrack/osm-routes-index#4]
For example https://routes.tracestrack.com/ie/hiking/all/ lists 2 routes, and https://routes.tracestrack.com/gb/hiking/all/ lists 137.  When I run a query on a database with IE and GB in it I get 1614:

gis=> select count(*)  from planet_osm_line where highway = 'ldpnwn' and ref != '';
 count
 -------
 1614
(1 row)

The database population lua code is at https://github.com/SomeoneElseOSM/SomeoneElse-style/blob/master/style.lua#L9908 if you're curious, and it also includes IoM, Jersey, Guernsey etc., and also some semicolon-separated networks like "lwn;lcn;lhn".  That doesn't account for the different between 139 and 1614 though?

Are you perhaps missing some, or am I misunderstanding what you're listing?

**Comment by quinncnl** [comment]
Hi! I think there is some misunderstanding indeed. The project lists route relations rather than plain ways. So the table should be `planet_osm_rels` instead of `planet_osm_line`. The SQL that dumps the hiking data list is this: https://github.com/tracestrack/osm-routes-index/blob/main/generator/dump_hiking_routes.sql

As you can see, it queries relations where `route` is either `foot' or 'hike`.

**Comment by SomeoneElseOSM** [comment]
> The project lists route relations rather than plain ways

Sorry - I should have made it clearer.  My "1614" number above is route relations.

> `hike`

Oops that's [not a typo](https://github.com/tracestrack/osm-routes-index/blob/main/generator/dump_hiking_routes.sql#L10)**, and https://taginfo.openstreetmap.org/keys/route#values suggests "hiking" rather than "hike".  Also http://taginfo.geofabrik.de/europe/great-britain/keys/route#values suggests > 3k usage of "hiking" and "foot" in GB.  I suppress some based on network tags, and some will be misused on e.g. nodes and ways, which will cut it down to (I'm guessing) 1200 or so for GB, assuming that 400 or so are IE (and I'm suppressing "ref", as you are, above) .

** and someone on Mastodon [also spotted that](https://en.osm.town/@alan/110492489851838063) before I did!

**Comment by quinncnl** [comment]
Ah! Right🙈 not `hike` but `hiking`! I'll update the query and hopefully it'll match your numbers!

**Comment by SomeoneElseOSM** [comment]
> hopefully it'll match your numbers!

It'll be closer - [overpass](https://overpass-turbo.eu/s/1vMh) suggests 146 rather than 137 (subtracting the 2 in Ireland).

You might want to consider your assumption that "all trails have a `ref`" as well...

**Comment by SomeoneElseOSM** [comment]
There are now 2890 at https://routes.tracestrack.com/gb/hiking/all/ - much more plausible!
